apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: liberty-app
spec:
  template:
    spec:
      containers:
      - name: liberty
        image: image-registry.openshift-image-registry.svc:5000/liberty-demo-prod/liberty-app
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
