apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: liberty-app-analysis
spec:
  metrics:
  - name: success-rate
    initialDelay: 30s
    interval: 30s
    count: 3
    successCondition: result >= 0.95
    provider:
      prometheus:
        address: http://prometheus-operated.openshift-monitoring.svc:9090
        query: |
          sum(rate(http_requests_total{job="liberty-app",status!~"5.."}[2m]))
          /
          sum(rate(http_requests_total{job="liberty-app"}[2m]))
